### ISSUE TITLE
Issue with Oracle

### ISSUE THREAD

**Issue by mjbros** [dkoudela/advanced-ldap-for-crucible#1]
I can't install this plugin with an Oracle 11G database

Exception in thread "ThreadPoolAsyncTaskExecutor::Thread 17" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'advancedLdapOptionsDAO' defined in URL [bundle://86.0:0/META-INF/spring/atlassian-plugins-components.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.davidkoudela.crucible.config.HibernateAdvancedLdapPluginConfigurationDAOImpl]: Constructor threw exception; nested exception is java.lang.Exception: org.hibernate.HibernateException: Dialect class not found: com.cenqua.crucible.hibernate.dialects.OracleLargeStringsDialect
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:883)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:839)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:440)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory$1.run(AbstractAutowireCapableBeanFactory.java:409)
 at java.security.AccessController.doPrivileged(Native Method)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:380)
 at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:264)
 at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
 at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:261)
 at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:185)
 at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:164)
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:429)
 at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:728)
 at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext.access$1600(AbstractDelegatedExecutionApplicationContext.java:69)
 at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext$4.run(AbstractDelegatedExecutionApplicationContext.java:355)
 at org.springframework.osgi.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85)
 at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext.completeRefresh(AbstractDelegatedExecutionApplicationContext.java:320)
 at org.springframework.osgi.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$CompleteRefreshTask.run(DependencyWaiterApplicationContextExecutor.java:132)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
 Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.davidkoudela.crucible.config.HibernateAdvancedLdapPluginConfigurationDAOImpl]: Constructor threw exception; nested exception is java.lang.Exception: org.hibernate.HibernateException: Dialect class not found: com.cenqua.crucible.hibernate.dialects.OracleLargeStringsDialect
 at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:115)
 at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:61)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:877)
 ... 20 more
 Caused by: java.lang.Exception: org.hibernate.HibernateException: Dialect class not found: com.cenqua.crucible.hibernate.dialects.OracleLargeStringsDialect
 at com.davidkoudela.crucible.config.HibernateSessionFactoryFactory.createHibernateSessionFactory(HibernateSessionFactoryFactory.java:72)
 at com.davidkoudela.crucible.config.HibernateAdvancedLdapPluginConfigurationDAOImpl.<init>(HibernateAdvancedLdapPluginConfigurationDAOImpl.java:25)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
 at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:100)
 ... 22 more
 Caused by: org.hibernate.HibernateException: Dialect class not found: com.cenqua.crucible.hibernate.dialects.OracleLargeStringsDialect
 at org.hibernate.dialect.resolver.DialectFactory.constructDialect(DialectFactory.java:160)
 at org.hibernate.dialect.resolver.DialectFactory.buildDialect(DialectFactory.java:109)
 at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:138)
 at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2163)
 at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2159)
 at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1383)
 at com.davidkoudela.crucible.config.HibernateSessionFactoryFactory.createHibernateSessionFactory(HibernateSessionFactoryFactory.java:63)
 ... 28 more
 Caused by: java.lang.ClassNotFoundException: com.cenqua.crucible.hibernate.dialects.OracleLargeStringsDialect
 at org.apache.felix.framework.ModuleImpl.findClassOrResourceByDelegation(ModuleImpl.java:772)
 at org.apache.felix.framework.ModuleImpl.access$200(ModuleImpl.java:73)
 at org.apache.felix.framework.ModuleImpl$ModuleClassLoader.loadClass(ModuleImpl.java:1690)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 at java.lang.Class.forName0(Native Method)
 at java.lang.Class.forName(Class.java:260)
 at org.hibernate.util.ReflectHelper.classForName(ReflectHelper.java:192)
 at org.hibernate.dialect.resolver.DialectFactory.constructDialect(DialectFactory.java:157)
 ... 34 more

**Comment by dkoudela** [comment]
Thank you for the report.
I will investigate the issue.

**Comment by znoorsazali** [comment]
I hit into the same, seems like a class is missing?

Caused by: java.lang.ClassNotFoundException: com.cenqua.crucible.hibernate.dialects.OracleLargeStringsDialect

I tested this on FeCru 3.8.1 and Oracle XE 11.2.0.2.0

**Comment by dkoudela** [comment]
I have found the root cause and I am working on the fix.
Thanks for the report.

**Comment by dkoudela** [comment]
The issue has been fixed.
I will inform you once it is released. I have to consider another changes. 
I will keep the issue open until it is released.

**Comment by dkoudela** [comment]
It has been released in v1.2

**Comment by mjbros** [comment]
Still seeing an issue

540445 [qtp549293029-1825] WARN org.hibernate.util.JDBCExceptionReporter - SQL Error: 12505, SQLState: 66000
540445 [qtp549293029-1825] ERROR org.hibernate.util.JDBCExceptionReporter - Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor

Hibernate get failed for Configuration data: org.hibernate.exception.GenericJDBCException: Cannot open connection
540465 [qtp549293029-1825] WARN org.hibernate.util.JDBCExceptionReporter - SQL Error: 12505, SQLState: 66000
540466 [qtp549293029-1825] ERROR org.hibernate.util.JDBCExceptionReporter - Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor

AdvancedLdapConfigurationAdminServlet.doPost: hibernateAdvancedLdapPluginConfigurationDAO.store failed: java.lang.Exception: Could not save key

**Comment by dkoudela** [comment]
This is different kind of error.
JDBC driver cannot connect to the database - oracle listener does not know the SID.
Are you able to connect to the database manually (e.g. by sqlplus) ?

**Comment by dkoudela** [comment]
Additionally, I would also check the listener.ora file.
Example:
```
SID_LIST_LISTENER = (SID_LIST = 
  (SID_DESC = (ORACLE_HOME = /opt/oracle/product/11.2) (SID_NAME = crucible))
  (SID_DESC = (ORACLE_HOME = /opt/oracle/product/11.2) (SID_NAME = crucibleadld))
)
```

**Comment by dkoudela** [comment]
Please let me know if you need any further help.

**Comment by mjbros** [comment]
The crucible DB login configuration is stored in the $FISHEYE_HOME/config.xml, where is the advanced LDAP DB login configured. Our DBA's have a naming standard for schema users that we have to follow

**Comment by mjbros** [comment]
Is the schema user and password hardcoded? Does it pick up the same URL as the database connection for crucible?

**Comment by dkoudela** [comment]
Well, the database parameters (DB Type, URL, User Name, Password, etc.) are the same as the Crucible DB, except the database name (portion of the DB URL). The parameters are taken from the same source: the Crucible configuration.
It is done that way for simplicity.

At the first release, it was not considered to be configurable separately from the Crucible configuration.
If you would like to have the plugin DB parameters configurable separately, please create an Issue and I will consider it in the next release.
Thanks a lot.

**Comment by znoorsazali** [comment]
David,
Can you provide a list of tables that will be created by the plugin? I am looking to test this locally and have some trouble granting access to a single user in Oracle to reading multiple database/schema. 
Thanks.

**Comment by dkoudela** [comment]
Hi,

there is currently only one table in the database:
AD_LDAP_PLUG_CONF_V2
Later on, there will be more.

Best Regards,
David.
